# Generated by Django 4.0.4 on 2022-06-12 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('新規', '新規'), ('確認中', '確認中'), ('完了', '完了')], max_length=50)),
                ('category_system', models.CharField(blank=True, choices=[('業務', '業務'), ('規則', '規則'), ('その他', 'その他')], max_length=50)),
                ('category_detail', models.CharField(blank=True, choices=[('全社', '全社'), ('営業', '営業'), ('仕入', '仕入'), ('経理', '経理'), ('物流', '物流'), ('ICT', 'ICT'), ('社内', '社内'), ('社外', '社外')], max_length=50)),
                ('questioner', models.CharField(max_length=100)),
                ('question_title', models.CharField(max_length=200)),
                ('question_contents', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
